// const express = require("express");
// var PostController = require("./../Controllers/POST_CONTROLLER");

// var router = express.Router();

// // router.route("/").get(PostController.getUsers).post(UserController.createUser);
// router.route("/").post(PostController.createPost);

// // router
// //   .route("/:id")
// //   .get(UserController.getUser)
// //   .patch(UserController.updateUser)
// //   .delete(UserController.deleteUser);

// module.exports = router;
